package(default_visibility = ["//visibility:public"])

java_library(
  name = 'entity',
  srcs = glob(['*.java']),
  deps = [
    '@org_hibernate_hibernate_core//jar',
    '@javax_persistence_javax_persistence_api//jar',
  ],
)